### ISSUE TITLE
Break transects on hunt area boundaries, and if transect is long

### ISSUE THREAD

**Issue by jcarlis3** [jcarlis3/pronghornLT#8]
Modify `makeLines` function with 3 primary goals:

**1. Constrain each transect to only intersect one hunt area.
Potential workflow:**
- Store hunt area (HA) boundaries in package
- Lay out transects as usual
- Identify points of intersection between HA boundaries and transects (`sf::st_intersection`?)
- Buffer those points by 1 km (`st_buffer`)
- Cut those circles out of the lines to create the break between lines (`st_difference`?)

**2. Constrain transects to a maximum length**
Potential workflow:
- After laying out transects and cutting on HU boundaries
- Measure length of each transect (`st_length`)
- If > 40 km, find center of line (`st_centroid`)
- Buffer and cut as above

**3. Assign each transect a meaningful name**
Potential workfow:
- After cutting by HA and if too long
- Assign each a unique "LineID", composite of HA and sequential number (e.g., 52-1, 52-2, ..., n_lines)
- Order from West to East, North to South.
- Other meaningful attributes to include:  HerdUnit, HuntArea, LineID, LengthKm, LengthMi

**Comment by jcarlis3** [comment]
@grcatlin , one lingering issue.

When naming transects, number from West to East, North to South.   See below, with "4" north of "5".  Current code puts "5" north of "4".

![image](https://user-images.githubusercontent.com/10441106/235739226-d759956e-7e81-4f3a-9c57-b95c5041f75e.png)

**Comment by grcatlin** [comment]
@jcarlis3 ordering should be fixed now
